config/routes.rb
Rails.application.routes.draw do
  root 'landing_page#home'
  get '/tos',       to: 'landing_page#tos'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
    get 'pass_edit', to: 'users/registrations#pass_edit', as: 'pass_edit'
    patch 'pass_update', to: 'users/registrations#pass_update', as: 'pass_update'
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] 
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :photos, only: [:new, :index, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="photos">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse header">
  <div>
    <%= link_to "Instagram", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "検索フォーム", "#" %></li>
          <li><%= link_to "通知", "#" %></li>
          <li><%= link_to "Myページ", current_user %></li>
          <li><%= link_to "投稿画像一覧", photos_path %></li>
          <li><%= link_to "アップロード", new_photo_path %></li>
          <li><%= link_to "Users", users_path %></li>
        <% else %>
          <li><%= link_to "検索フォーム", "#" %></li>
          <li><%= link_to "通知", "#" %></li>
          <li><%= link_to "Myページ", new_user_session_path %></li>
          <li><%= link_to "アップロード", new_user_session_path %></li>
          <li><%= link_to "投稿画像一覧", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/shared/_photo_form.html.erb
<%= form_with(model: @photo, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "写真タイトルを入力してください。" %>
    <%= f.file_field :image, accept: "image/jpeg, image/png" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $("#photo_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('５MB以下の写真を選択してください。');
      $("#photo_image").val("");
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー数
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー数
  </a>
</div>

app/views/shared/_user_info.html.erb
<aside class="col-2 col-md-3">
  <%= link_to gravatar_for(@user, size: 180) %>
</aside>
<div class="name name-margin">
  <p>フルネーム：<%= @user.user_name %></p>
</div>
<div class="name">
  <p>ニックネーム：<%= @user.pen_name %></p>
</div>
<div>
  <%= render 'shared/stats' %>
  <div class="col-md-4 follow-margin">
    <%= render 'follow_form' if logged_in? %>
    <%= link_to_if(current_user == @user, "プロフィール編集", edit_user_registration_path){} %>
  </div>
</div>
<div class="profile-margin">
  <h3>【自己紹介】<br> <%= @user.introduction %></h3>
</div>
<div class="web-margin">
  <h4>【Webサイト】 <%= @user.website %></h4>
</div>